services:
  smartparking3d:
    build: .
    image: savik175/smartparking3d
    container_name: smartparking3d
    restart: always
    ports:
      - "8008:8008"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
